### ISSUE TITLE
URL down: https://whosonfirst.mapzen.com/bundles/index.txt

### ISSUE THREAD

**Issue by dr0i** [pelias/whosonfirst#334]
After `npm start` :
>  Error: Command failed: curl --silent -L https://whosonfirst.mapzen.com/bundles/index.txt
    at checkExecSyncError (child_process.js:574:11)

So I went to https://github.com/whosonfirst-data/whosonfirst-data and build the data as `*.pbf`. Referenced these in `~/pelias.conf` but without that `index.txt` (how does it looks like? Can I build it myself somehow) that doesn't work.

**Comment by orangejulius** [comment]
Hey @dr0i,

This should be fixed as of https://github.com/pelias/whosonfirst/pull/324 which was merged the other day. Can you try pulling the latest from this Github rebo and try again?

**Comment by dr0i** [comment]
Hi @orangejulius , that was quick I have to admit I am impressed!  Works like a charm, thx! :+1:

**Comment by orangejulius** [comment]
Glad to hear it. Please let me know if you encounter any other issues.

I'm glad you appreciated my fast reply. All Pelias Github repo activity goes straight to my inbox, so it may suffer a bit, but it's worth it :)

**Comment by dr0i** [comment]
Nice to see such good service! I will work again at monday, so don't expect any cry for help from me soon. Thx again!

**Comment by nilsnolde** [comment]
Sorry for re-opening this, but it still fails for me at the same line, just the domain changed
    Error: Command failed: curl --silent -L https://dist.whosonfirst.org/bundles/index.txt
    at checkExecSyncError (child_process.js:601:13)
Am I missing smth?

**Comment by orangejulius** [comment]
@nilsnolde,
The same is happening for me. How long has it been broken for you?

**Comment by nilsnolde** [comment]
Man, you're out-of-this-world quick..

Just tried it the first time to be honest.. In the middle of setting up a new instance, first time I'm not using `importPlace`.

**Comment by orangejulius** [comment]
Hah, thanks.

I will let the Who's on First folks know in a little bit. I suspect it will be fixed just as fast as DNS issues can be fixed which is often...not fast.

**Comment by nilsnolde** [comment]
Right.. No worries. Thanks to you and Peter, we should be ok for a while:) Let me know if I can do anything!

Thanks for taking care!

**Comment by orangejulius** [comment]
It should be fixed soonish. `http://dist.whosonfirst.org.s3.amazonaws.com/` will work until then if you really want that data

**Comment by nilsnolde** [comment]
For future reference:
The HTTPS version of S3 buckets don't work as expected with 'subdomains' containing a `.`, like `dist.whosonfirst.org`. Though Julian put the HTTP version of course. But somehow I ended up using HTTPS.

**Comment by orangejulius** [comment]
Yeah, this is an issue we've run into before with S3 buckets that aren't in `us-east-1`. Amazon does a lot of annoying things, but this is close to the top.
